config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check
  get '/menu', to: 'menus#menu'
  get '/burgers/:burger_name', to: 'burgers#show', as: 'burger_description'
  get '/burgers/:id/previous', to: 'burgers#previous', as: 'previous_burger'
  get '/burgers/:id/next', to: 'burgers#next', as: 'next_burger'
  get '/bonplans/:bonplan_name', to: 'bonplans#show', as: 'bon_plan_description'
  get '/bonplans/:id/previous', to: 'bonplans#previous', as: 'previous_bonplan'
  get '/bonplans/:id/next', to: 'bonplans#next', as: 'next_bonplan'
  get '/bowls/:bowl_name', to: 'bowls#show', as: 'bowl_description'
  get '/bowls/:id/previous', to: 'bowls#previous', as: 'previous_bowl'
  get '/bowls/:id/next', to: 'bowls#next', as: 'next_bowl'
  get '/drinks/:drink_name', to: 'drinks#show', as: 'drink_description'
  get '/drinks/:id/previous', to: 'drinks#previous', as: 'previous_drink'
  get '/drinks/:id/next', to: 'drinks#next', as: 'next_drink'
  get '/sides/:side_name', to: 'sides#show', as: 'side_description'
  get '/sides/:id/previous', to: 'sides#previous', as: 'previous_side'
  get '/sides/:id/next', to: 'sides#next', as: 'next_side'
  get '/desserts/:dessert_name', to: 'desserts#show', as: 'dessert_description'
  get '/desserts/:id/previous', to: 'desserts#previous', as: 'previous_dessert'
  get '/desserts/:id/next', to: 'desserts#next', as: 'next_dessert'
  get '/starters/:starter_name', to: 'starters#show', as: 'starter_description'
  get '/starters/:id/previous', to: 'starters#previous', as: 'previous_starter'
  get '/starters/:id/next', to: 'starters#next', as: 'next_starter'
  get '/menus/:menu_name', to: 'menus#show', as: 'menu_description'
  get '/franchise', to: 'franchise#franchise'
  get 'localisation', to: 'localisations#index', as: 'localisation'
  post 'submit_form', to: 'forms#submit'

  get '/restaurants/:name', to: 'restaurants#show', as: 'restaurant_show'

  get '/restaurants/:id/previous', to: 'restaurants#previous', as: 'previous_restaurant'
  get '/restaurants/:id/next', to: 'restaurants#next', as: 'next_restaurant'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bon_plan.rb
class BonPlan < ApplicationRecord
end

app/models/bowl.rb
class Bowl < ApplicationRecord
end

app/models/burger.rb
class Burger < ApplicationRecord
end

app/models/dessert.rb
class Dessert < ApplicationRecord
end

app/models/drink.rb
class Drink < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :restaurant_hours, class_name: 'RestaurantHour'
  validates :name, uniqueness: true

  def current_status
    current_time = Time.now.in_time_zone('Europe/Paris')
    current_day = current_time.strftime("%A").downcase

    open_time_str = self.send("#{current_day}_open")
    close_time_str = self.send("#{current_day}_close")

    return "FERMÉ" if open_time_str.nil? || close_time_str.nil?

    open_time = Time.zone.parse("#{current_time.strftime('%Y-%m-%d')} #{open_time_str}")
    close_time = Time.zone.parse("#{current_time.strftime('%Y-%m-%d')} #{close_time_str}")

    if close_time < open_time
      close_time += 1.day
    end

    if current_time >= open_time && current_time <= close_time
      "OUVERT jusqu'à #{close_time.strftime('%H:%M')}"
    else
      "FERMÉ jusqu'à #{open_time.strftime('%H:%M')}"
    end
  end
end

app/models/side.rb
class Side < ApplicationRecord
end

app/models/starter.rb
class Starter < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/bonplans_controller.rb
class BonplansController < ApplicationController
  def show
    @bonplan = BonPlan.find_by(name: params[:bonplan_name])
  end

  def previous
    @bonplan = BonPlan.where("id < ?", params[:id]).last || BonPlan.last
    redirect_to bonplan_description_path(bonplan_name: @bonplan.name)
  end

  def next
    @bonplan = BonPlan.where("id > ?", params[:id]).first || BonPlan.first
    redirect_to bon_plan_description_path(bonplan_name: @bonplan.name)
  end
end

app/controllers/bowls_controller.rb
class BowlsController < ApplicationController
  def show
    @bowl = Bowl.find_by(name: params[:bowl_name])
  end

  def previous
    @bowl = Bowl.where("id < ?", params[:id]).last || Bowl.last
    redirect_to bowl_description_path(bowl_name: @bowl.name)
  end

  def next
    @bowl = Bowl.where("id > ?", params[:id]).first || Bowl.first
    redirect_to bowl_description_path(bowl_name: @bowl.name)
  end
end

app/controllers/burgers_controller.rb
class BurgersController < ApplicationController
  def show
    @burger = Burger.find_by(name: params[:burger_name])
  end

  def previous
    @burger = Burger.where("id < ?", params[:id]).last || Burger.last
    redirect_to burger_description_path(burger_name: @burger.name)
  end

  def next
    @burger = Burger.where("id > ?", params[:id]).first || Burger.first
    redirect_to burger_description_path(burger_name: @burger.name)
  end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  def show
    @drink = Drink.find_by(name: params[:drink_name])
  end

  def previous
    @drink = Drink.where("id < ?", params[:id]).last || Drink.last
    redirect_to drink_description_path(drink_name: @drink.name)
  end

  def next
    @drink = Drink.where("id > ?", params[:id]).first || Drink.first
    redirect_to drink_description_path(drink_name: @drink.name)
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def submit
    form_data = params[:responses]
    Rails.logger.info "Received responses: #{form_data.inspect}"

    UserMailer.contact_email(form_data).deliver_now

    render json: { message: 'Success' }, status: :ok
  rescue => e
    Rails.logger.error "Error sending email: #{e.message}"
    render json: { message: 'Error', error: e.message }, status: :unprocessable_entity
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def menu
    @menus = Menu.all
    @burgers = Burger.all
    @bowls = Bowl.all
    @starters = Starter.all
    @bonplans = BonPlan.all
    @drinks = Drink.all
    @sides = Side.all
    @desserts = Dessert.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/controllers/sides_controller.rb
class SidesController < ApplicationController
  def show
    @side = Side.find_by(name: params[:side_name])
  end

  def previous
    @side = Side.where("id < ?", params[:id]).last || Side.last
    redirect_to side_description_path(side_name: @side.name)
  end

  def next
    @side = Side.where("id > ?", params[:id]).first || Side.first
    redirect_to side_description_path(side_name: @side.name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Navbar</title>
  <style>
    @font-face {
      font-family: 'GomuRegular';
      src: url('Gomu-Regular.otf') format('opentype');
    }

    .container-fluid {
      font-family: 'GomuBold' !important;
      letter-spacing: 1px;
      font-size: 22px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 0 10%;
      position: relative;
    }
    .navbar {
      background-color: transparent !important;
      transition: top 0.9s;
      height: 15vh;
      display: flex;
      align-items: center;
      justify-content: space-between;
      width: 100%;
      padding: 0;
    }
    .nav-link {
      font-family: 'GomuBold' !important;
      font-weight: normal;
      color: #ffffff !important;
      transition: transform 0.3s ease;
    }
    .nav-link:hover {
      color: #e163f2 !important;
      transform: scale(1.1);
    }
    .nav-link.active {
      color: #6623FF !important;
      background-color: transparent !important;
    }
    .nav-item {
      margin: 0 10px;
    }
    .left-nav, .right-nav {
      display: flex;
      align-items: center;
      flex: 1;
    }
    .left-nav {
      justify-content: flex-end;
      margin-right: 4.375rem;
    }
    .right-nav {
      justify-content: flex-start;
      margin-left: 4.375rem;
    }
    .navbar-brand {
      position: absolute;
      left: 50%;
      transform: translateX(-50%);
    }
    .navbar-brand img {
      transition: transform 0.3s ease;
    }
    .navbar-brand img:hover {
      transform: scale(1.1);
    }
    .responsive-logo {
      height: 80px;
    }
    @media (max-width: 768px) {
      .left-nav, .right-nav {
        display: none;
      }
      .navbar-brand {
        position: relative;
        left: auto;
        transform: none;
      }
      .collapse {
        display: flex;
        flex-direction: column;
        align-items: center;
      }
      .collapse .navbar-nav {
        flex-direction: column;
      }
    }
    @media (max-width: 375px) {
      .responsive-logo {
        height: 60px;
      }
    }

  </style>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="<%= root_path %>">
        <img src="<%= asset_path('LOGO/gomu-logowhite.webp') %>" alt="Logo" class="responsive-logo">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <div class="left-nav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "CONCEPT", "#", class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "LOCALISATION", localisation_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
        <div class="right-nav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "MENU", menu_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "DEVENIR FRANCHISÉ", franchise_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script>
    function setActiveLink() {
      const currentPath = window.location.pathname;
      const navLinks = document.querySelectorAll('.nav-link');

      navLinks.forEach(link => {
        if (link.getAttribute('href') === currentPath) {
          link.classList.add('active');
        } else {
          link.classList.remove('active');
        }
      });
    }

    setActiveLink();
    window.addEventListener('popstate', setActiveLink);
    document.querySelectorAll('.navbar a').forEach(link => {
      link.addEventListener('click', function() {
        setTimeout(setActiveLink, 100);
      });
    });
  </script>
</body>
</html>